CREATE DATABASE prueba2
USE prueba2
CREATE TABLE CLIENTES(
	idnombre INT PRIMARY KEY NOT NULL,
	NOMBRE TEXT,
	DIRECCION TEXT)
	
CREATE TABLE PRODUCTOS(
	idproducto INT PRIMARY KEY NOT NULL,
	NOMBRE TEXT,
	CANTIDAD INT
	)
	
CREATE TABLE VENTAS(
	Idventas INT PRIMARY KEY NOT NULL,	
	idnombre int REFERENCES CLIENTES (idnombre),
	idproducto int REFERENCES PRODUCTOS (idproducto)  
	)
