CREATE DATABASE prueba3
USE prueba3
CREATE TABLE CLIENTES(
	idnombre INT PRIMARY KEY NOT NULL,
	NOMBRE TEXT,
	DIRECCION TEXT)
	
CREATE TABLE PRODUCTOS(
	idproducto INT PRIMARY KEY NOT NULL,
	NOMBRE TEXT,
	CANTIDAD INT
	)
	
CREATE TABLE VENTAS(
	idventas INT PRIMARY KEY NOT NULL,
	idnombre INT FOREIGN KEY(idnombre) REFERENCES CLIENTES,
	idproducto INT FOREIGN KEY(idproducto) REFERENCES PRODUCTOS  
	)
